### ISSUE TITLE
[Feature Request] Make plugin fully reloadable

### ISSUE THREAD

**Issue by alexis-evelyn** [alexis-evelyn/InternetRedstone#1]
## TODO:
- [ ] Be Able to Reload MySQL From Config Reload
- [ ] Be Able to Reload MQTT Topics From Config Reload
- [ ] Be Able to Change Topic IGN on User Login
- [ ] Be Able to Fail Gracefully on Invalid MySQL Parameters (so, nice error message and ability to reload)
- [ ] Be Able to Fail Gracefully on Invalid MQTT Parameters (so, nice error message and ability to reload)
